package age.of.civilizations2.jakowski.lukasz.GameValues;

public class GV_AllianceOffer {
    public int COST_OFFER_ALLIANCE_DIPLOMACY_POINTS = 20;
    public int COST_ALLIANCE_LEAVE = 2;
    public int SCORE_POSITIVE_HRE = 4;
    public float SCORE_POSITIVE_RELATION_MODIFIER = 0.515f;
    public int SCORE_POSITIVE_SAME_GOVERNMENT = 4;
    public int SCORE_POSITIVE_SAME_GOVERNMENT_GROUP = 1;
    public int SCORE_POSITIVE_DIFFERENT_GOVERNMENT = 0;
    public int SCORE_POSITIVE_SAME_RELIGION = 4;
    public int SCORE_POSITIVE_SAME_RELIGION_GROUP = 1;
    public int SCORE_POSITIVE_DIFFERENT_RELIGION = 0;
    public float SCORE_NEGATIVE_RELATION_MODIFIER = 0.5f;
    public int SCORE_NEGATIVE_RELATION_BELOW_X_VALUE = 0;
    public int SCORE_NEGATIVE_RELATION_BELOW_X_PENALTY = 5;
    public int SCORE_NEGATIVE_HRE_MEMBERSHIP_DIFFERENCE = -6;
    public int SCORE_NEGATIVE_GOVERNMENT_SAME_GROUP = 0;
    public int SCORE_NEGATIVE_GOVERNMENT_DIFFERENT_GROUP_AND_GOVERNMENT = -14;
    public int SCORE_NEGATIVE_RELIGION_SAME_GROUP = 0;
    public int SCORE_NEGATIVE_RELIGION_DIFFERENT_GROUP_AND_RELIGION = -16;
    public float SCORE_NEGATIVE_POWERFUL_ALLIES_ALLY_RANK_PENALTY_MULTIPLIER = 10.0f;
    public float SCORE_NEGATIVE_POWERFUL_ALLIES_ALLY_RANK_PENALTY_LIMIT = 12.0f;
    public float SCORE_NEGATIVE_POWERFUL_ALLIES_OPINION_WEIGHT = 0.715f;
    public int SCORE_NEGATIVE_CIV_AT_WAR = -250;
    public int SCORE_NEGATIVE_EMBASSY_CLOSED = -1000;
    public int SCORE_NEGATIVE_IS_VASSAL = -250;
    public int SCORE_NEGATIVE_CORE_PENALTY_BASE = 15;
    public int SCORE_NEGATIVE_PER_EXTRA_CORE = 5;
    public int SCORE_NEGATIVE_CORE_PENALTY_MAX = 30;
    public float SCORE_NEGATIVE_DISTANCE_MODIFIER = 0.5f;
}
