package age.of.civilizations2.jakowski.lukasz.GameValues;

public class GV_Assimilate {
    public int COST_ASSIMILATE_MOVEMENT = 4;
    public int ASSIMILATE_NUM_OF_TURNS_MIN = 10;
    public int ASSIMILATE_NUM_OF_TURNS_MAX = 50;
    public int BASE_COST_OF_ASSIMILATE = 500;
    public float COST_OF_ASSIMILATE_INCOME_TAXATION = 1.275f;
    public float COST_OF_ASSIMILATE_INCOME_PRODUCTION = 0.937f;
    public float COST_OF_ASSIMILATE_BASE_MODIFIER_DEVELOPMENT = 0.885f;
    public float COST_OF_ASSIMILATE_MODIFIER_DEVELOPMENT = 0.45f;
    public float COST_OF_ASSIMILATE_MODIFIER_CIV_ASSIMILATION_IN_PROGRESS = 0.0825f;
    public float COST_OF_ASSIMILATE_MODIFIER_DISTANCE = 1.0f;
    public float COST_OF_ASSIMILATE_BASE_MODIFIER_POPULATION_PERC = 1.625f;
    public float ASSIMILATE_HAPPINESS_CHANGE_PER_TURN = -0.005f;
    public float AI_ASSIMILATE_MIN_GOLD_MODIFIER = 1.225f;
    public float BASE_ASSIMILATION_RATE = 0.00425f;
    public float ASSIMILATION_SCALING_BASE = 0.04971f;
    public int ASSIMILATION_SCALING_RANDOM_10000 = 1087;
    public float ASSIMILATION_DEVELOPMENT_DIVIDER = 3.75f;
    public float ASSIMILATION_INSTABILITY_PENALTY = 0.225f;
    public float ASSIMILATION_REVOLUTION_RISK_PENALTY = 0.075f;
    public float ASSIMILATION_FINAL_MULTIPLIER = 0.8f;
    public int CREATE_NEW_GAME_MAX_ASSIMILATE_SPEED = 500;
}
