package age.of.civilizations2.jakowski.lukasz.GameValues;

public class GV_Battle {
    public int TECHNOLOGY_LEVEL_BONUS_ARMY_DEFENSE_DEFAULT = 100;
    public int TECHNOLOGY_LEVEL_BONUS_ARMY_DEFENSE_LIMIT = 300;
    public int TECHNOLOGY_LEVEL_BONUS_ARMY_ATTACK_DEFAULT = 110;
    public int TECHNOLOGY_LEVEL_BONUS_ARMY_ATTACK_LIMIT = 300;
    public float BATTLE_PROVINCE_ECONOMY_LOSSES_UNITS = 0.00275f;
    public float BATTLE_PROVINCE_ECONOMY_LOSSES_MAX_PERC = 0.035f;
    public float BATTLE_PROVINCE_POPULATION_LOSSES_BASE = 0.0305f;
    public float BATTLE_PROVINCE_POPULATION_LOSSES_TECH_LEVEL_MODIFIER = 0.0065f;
    public float BATTLE_PROVINCE_POPULATION_LOSSES_OR_BASED_ON_POPULATION_PERC = 0.0025f;
}
