package age.of.civilizations2.jakowski.lukasz.GameValues;

public class GV_Colonize {
    public int COLONIZE_COST_MOVEMENT_POINTS_MAX = 40;
    public float COLONIZE_COST_MOVEMENT_POINTS_DISTANCE_MODIFIER = 1.6275f;
    public float COLONIZE_COST_GOLD_GROWTH_RATE_MODIFIER = 0.0845f;
    public float COLONIZE_COST_GOLD_DISTANCE_MODIFIER = 0.1325f;
    public float COLONIZE_COST_GOLD_SAME_REGION_AND_CONTINENT_MODIFIER = 0.815f;
    public float COLONIZE_COST_GOLD_SAME_REGION_MODIFIER = 0.915f;
    public float COLONIZE_COST_GOLD_SAME_CONTINENT_MODIFIER = 0.865f;
    public float COLONIZE_COST_GOLD_NONE_MODIFIER = 1.0f;
    public float COLONIZE_COST_REDUCTION_SAME_CIV_NEIGHBORING_PROVINCES_PERC = -0.4f;
    public float COLONIZE_COST_PENALTY_LOW_TECH_BASE = 2.675f;
    public float COLONIZE_COST_PENALTY_LOW_TECH_DIFFERENCE_MODIFIER = 8.25f;
    public int BASE_POPULATION = 500;
    public int BASE_ECONOMY_MIN = 250;
    public int NEW_COLONY_BONUS = 50;
    public float NEW_COLONY_GROWTH_RATE_BONUS_BASE = 0.122f;
    public float NEW_COLONY_GROWTH_RATE_BONUS_PERC_OF_PROVINCE_GROWTH = 0.238f;
    public int COLONIZE_ARMY_MIN = 25;
    public int COLONIZE_ARMY_RANDOM = 25;
    public int HAPPINESS_MIN = 62;
    public int HAPPINESS_RANDOM = 31;
    public float DEVELOPMENT_MIN = 0.125f;
    public int DEVELOPMENT_RANDOM_1000 = 100;
    public float NEUTRAL_POPULATION_ASSIMILATION_BASE = 0.375f;
    public int NEUTRAL_POPULATION_ASSIMILATION_RANDOM_100 = 35;
    public int COLONIZATION_AUTO_EXPAND_CHANCE_100_DEFAULT = 95;
}
