package age.of.civilizations2.jakowski.lukasz.GameValues;

public class GV_EconomyGrowth {
    public float ECO_GROWTH_STARTING_POPULATION_MODIFIER = 0.0825f;
    public float ECO_GROWTH_BASE_VALUE = 0.65f;
    public float ECO_GROWTH_PROV_DEVELOPMENT_PERC_OF_TECH_MODIFIER = 0.275f;
    public float ECO_GROWTH_PROV_GROWTH_RATE_MODIFIER = 0.075f;
    public float ECO_GROWTH_LOW_ECONOMY_BONUS_BASE = 0.00425f;
    public float ECO_GROWTH_LOW_ECONOMY_BONUS_PROV_GROWTH_RATE_MODIFIER = 0.7548f;
    public float ECO_GROWTH_LOW_ECONOMY_BONUS_PROV_DEVELOPMENT_MODIFIER = 3.165134f;
    public float ECO_GROWTH_MODIFIER_STARTING_ECONOMY_MODIFIER = 1.4681f;
    public float ECO_GROWTH_MODIFIER_STARTING_ECONOMY_MIN = 0.086486f;
    public float ECO_GROWTH_MODIFIER_FINAL_BASE_PERC = 0.1f;
    public float ECO_GROWTH_MODIFIER_FINAL_RANDOM_POSITIVE_PERC = 1.0f;
    public int ECO_GROWTH_MODIFIER_FINAL_RANDOM_POSITIVE_MIN_VALUE = 4;
    public float ECO_GROWTH_MODIFIER_FINAL_RANDOM_NEGATIVE_PERC = 0.25f;
}
