package age.of.civilizations2.jakowski.lukasz.GameValues;

public class GV_Goods {
    public float GOODS_BELOW_MIN_HAPPINESS_BASE_MODIFIER = -0.01225f;
    public float GOODS_BELOW_MIN_HAPPINESS_BASE_DEV_POP_GROWTH_MODIFIER = 0.01f;
    public float GOODS_BELOW_MIN_HAPPINESS_PROVINCE_DEVELOPMENT_MODIFIER = 1.25f;
    public float GOODS_BELOW_MIN_HAPPINESS_PROVINCE_GROWTH_RATE_MODIFIER = 0.135f;
    public float GOODS_BELOW_MIN_HAPPINESS_WAR_WEARiNESS_MODIFIER = -0.625f;
    public float GOODS_BELOW_MIN_ECONOMY_BASE_MODIFIER = -0.00625f;
    public float GOODS_BELOW_MIN_ECONOMY_BASE_DEV_POP_GROWTH_MODIFIER = 0.01f;
    public float GOODS_BELOW_MIN_ECONOMY_PROVINCE_DEVELOPMENT_MODIFIER = 0.5475f;
    public float GOODS_BELOW_MIN_ECONOMY_PROVINCE_GROWTH_RATE_MODIFIER = 0.195f;
}
