package age.of.civilizations2.jakowski.lukasz.GameValues;

public class GV_MoveCapital {
    public float MOVE_CAPITAL_HAPPINESS_CHANGE_OLD = 0.12168f;
    public float MOVE_CAPITAL_HAPPINESS_CHANGE_NEW = 0.025f;
    public int MOVE_CAPITAL_LOCK_MOVING_FOR_X_TURNS = 50;
    public int MOVE_CAPITAL_COST_WHEN_NO_CAPITAL = 25;
    public float MOVE_CAPITAL_COST_GOLD_BASE_VALUE = 10.0f;
    public float MOVE_CAPITAL_COST_GOLD_STARTING_POPULATION_PERC = 0.1925f;
    public float MOVE_CAPITAL_COST_GOLD_PROVINCE_POPULATION_PERC = 0.125f;
    public float MOVE_CAPITAL_INCOME_MULTIPLIER_BASE = 2.1348f;
    public float MOVE_CAPITAL_INCOME_MULTIPLIER_TECH_FACTOR = 1.86584f;
}
