package age.of.civilizations2.jakowski.lukasz.GameValues;

public class GV_PopulationGrowth {
    public int GROWTH_AND_DECLINE_MENU_CIVS_LIMIT = 50;
    public float POP_GROWTH_BASE_VALUE = 0.2f;
    public float POP_GROWTH_BASE_VALUE_GOODS_SPENDING_OVER = 0.5f;
    public int POP_GROWTH_BASE_VALUE_GOODS_SPENDING_BELOW_RANDOM_100_MAX = 50;
    public float POP_GROWTH_PROVINCE_GROWTH_RATE_BASE = 0.01f;
    public float POP_GROWTH_PROVINCE_GROWTH_RATE_MODIFIER = 0.485f;
    public float POP_GROWTH_PROVINCE_DEVELOPMENT_MODIFIER = 0.0156f;
    public float POP_GROWTH_LOW_POPULATION_BONUS_BASE = 0.00725f;
    public float POP_GROWTH_LOW_POPULATION_BONUS_DEVELOPMENT_MODIFIER = 2.7469234f;
    public float POP_GROWTH_LOW_POPULATION_BONUS_DEVELOPMENT_MODIFIER_LIMIT = 1.0f;
    public float POP_GROWTH_MODIFIER_STARTING_POPULATION_MODIFIER = 1.825f;
    public float POP_GROWTH_MODIFIER_STARTING_POPULATION_MIN = 0.0865f;
    public float POP_GROWTH_MODIFIER_FINAL_BASE_PERC = 0.1f;
    public float POP_GROWTH_MODIFIER_FINAL_RANDOM_POSITIVE_PERC = 1.0f;
    public int POP_GROWTH_MODIFIER_FINAL_RANDOM_POSITIVE_MIN_VALUE = 10;
    public float POP_GROWTH_MODIFIER_FINAL_RANDOM_NEGATIVE_PERC = 0.325f;
    public float POP_GROWTH_NATIONALITY_OWNER_X_STABILITY = 8.13f;
    public float POP_GROWTH_NATIONALITY_LORD = 1.83f;
    public float POP_GROWTH_NATIONALITY_TRUE_OWNER = 6.241138f;
    public float POP_GROWTH_NATIONALITY_CORE_CIV = 6.7861f;
    public float POP_GROWTH_NATIONALITY_NEIGHBORING_PROVINCE_CIV = 2.0f;
    public int POP_GROWTH_LIMIT_PER_TURN = 3500;
    public float POP_GROWTH_BUDGET_TEXT_RANDOM_MODIFIER = 0.75f;
    public int CREATE_NEW_GAME_MIN_POPULATION_GROWTH = 20;
    public int CREATE_NEW_GAME_MAX_POPULATION_GROWTH = 666;
}
