package age.of.civilizations2.jakowski.lukasz.GameValues;

public class GV_Plunder {
    public float PLUNDER_TAX_INCOME_MODIFIER = 1.45f;
    public float PLUNDER_INCOME_HIGH_REV_RISK_MODIFIER = 0.625f;
    public float PLUNDER_MIN_ARMY_POP_RATIO = 0.1375f;
    public float PLUNDER_MIN_ARMY_POP_RATIO_TECH_MODIFIER = -0.035f;
    public int PLUNDER_ECONOMY_LOSS_BASE_MIN = 4;
    public float PLUNDER_ECONOMY_LOSS_BASE_RATIO = 0.0425f;
    public int PLUNDER_ECONOMY_LOSS_RANDOM_RATIO_10000 = 525;
    public float PLUNDER_DEV_LOSS_BASE_RATIO = 0.0875f;
    public int PLUNDER_DEV_LOSS_RANDOM_RATIO_10000 = 625;
    public float PLUNDER_HAPPINESS_LOSS_BASE_RATIO = 0.05728f;
    public int PLUNDER_HAPPINESS_LOSS_RANDOM_RATIO_10000 = 426;
    public float PLUNDER_REV_RISK_BASE_RATIO = 0.011861f;
    public int PLUNDER_REV_RISK_RANDOM_RATIO_10000 = 268;
    public float PLUNDER_REV_RISK_MIN = 0.034378f;
    public float PLUNDER_POP_LOSS_BASE_RATIO_ARMY = 0.04864f;
    public int PLUNDER_POP_LOSS_RANDOM_RATIO_10000_ARMY = 412;
    public float PLUNDER_POP_LOSS_BASE_RATIO_POPULATION = 0.0786f;
    public int CREATE_NEW_GAME_MAX = 500;
}
