package age.of.civilizations2.jakowski.lukasz.GameValues;

public class GV_RebelsIndependence {
    public int UPDATE_EVERY_X_TURNS = 16;
    public int INDEPENDENCE_MIN_TURNS_SINCE_REVOLT_BASE = 10;
    public int INDEPENDENCE_MIN_TURNS_SINCE_REVOLT_RANDOM = 10;
    public int INDEPENDENCE_MIN_TURNS_SINCE_LAST_PROVINCE_LOST = 3;
    public int INDEPENDENCE_MAX_TURNS_BEFORE_FORCED_INDEPENDENCE = 49;
    public int NEW_CIV_INDEPENDENCE_CHOOSE_HIGHEST_POP_CHANCE_100 = 80;
    public float NEW_CIV_TECH_BASE_MODIFIER = 0.825f;
    public int NEW_CIV_TECH_RANDOM_MODIFIER_1000 = 35;
    public float NEW_CIV_CAPITAL_MIN_HAPPINESS = 0.92f;
    public float NEW_CIV_CAPITAL_POP_ASSIMILATE_BASE = 0.76f;
    public int NEW_CIV_CAPITAL_POP_ASSIMILATE_RANDOM_1000 = 240;
    public int NEW_CIV_CAPITAL_MIN_ASSIMILATED_POP = 250;
    public float NEW_CIV_CAPITAL_ECONOMY_GROWTH = 1.25f;
    public float NEW_CIV_CAPITAL_DEVELOPMENT_GROWTH = 1.25f;
    public float NEW_CIV_PROVINCE_HAPPINESS_MODIFIER = 1.1775f;
    public float NEW_CIV_PROVINCE_HAPPINESS_MIN = 0.82f;
    public int NEW_CIV_PROVINCE_HAPPINESS_RANDOM_100 = 18;
    public float NEW_CIV_PROVINCE_POP_ASSIMILATE_BASE = 0.67f;
    public int NEW_CIV_PROVINCE_POP_ASSIMILATE_RANDOM_1000 = 300;
    public float NEW_CIV_PROVINCE_POP_ASSIMILATE_ALREADY_EXISTING_CIV_BASE = 0.62f;
    public int NEW_CIV_PROVINCE_POP_ASSIMILATE_ALREADY_EXISTING_CIV_RANDOM_1000 = 310;
    public int NEW_CIV_MIN_GOLD = 500;
    public int NEW_CIV_MIN_GOLD_RANDOM = 4500;
}
