package age.of.civilizations2.jakowski.lukasz.GameValues;

public class GV_RebelsSupport {
    public int COST_SUPPORT_REBELS_DIPLOMACY_POINTS = 30;
    public int SUPPORT_REBELS_NUM_OF_TURNS_MAX = 35;
    public float SUPPORT_REBELS_ASSIMILATE_COST_MODIFIER = 1.6275f;
    public float SUPPORT_REBELS_ASSIMILATE_PERC = 0.845f;
    public float SUPPORT_REBELS_ASSIMILATE_MORE_SUPPORTERS_MODIFIER = 0.125f;
    public float SUPPORT_REBELS_RUN_BASE_POPULATION = 0.0065f;
    public float SUPPORT_REBELS_RUN_BASE_RANDOM = 0.04971f;
    public int SUPPORT_REBELS_RUN_RANDOM_OF_10000 = 1087;
    public float SUPPORT_REBELS_RUN_MIN_HAPPINESS_MODIFIER = 0.25f;
    public float SUPPORT_REBELS_RUN_HAPPINESS_MODIFIER = 1.0f;
    public float SUPPORT_REBELS_RUN_MIN_DEVELOPMENT_MODIFIER = 0.25f;
    public float SUPPORT_REBELS_RUN_DEVELOPMENT_MODIFIER = 0.2f;
    public float SUPPORT_REBELS_RUN_PER_REV_RISK_MODIFIER = 0.025f;
    public float SUPPORT_REBELS_MAX_COST_MODIFIER = 2.5f;
    public float SUPPORT_REBELS_MONEY_TO_POPULATION_RATIO_MODIFIER = 0.0747f;
    public float SUPPORT_REBELS_REV_RISK_CHANGE_BASE_VALUE = 0.275f;
}
