package age.of.civilizations2.jakowski.lukasz.GameValues;

public class GV_RelationDecrease {
    public int COST_OFFER_DECREASE_RELATIONS_DIPLOMACY_POINTS = 4;
    public int SUSPEND_DIPLOMATIC_RELATIONS_MAX = 100;
    public int SUSPEND_DIPLOMATIC_RELATIONS_MIN = 15;
    public int INSULT_DECREASE_RELATIONS = 30;
    public int INSULT_DECREASE_RELATIONS_RANDOM_VALUE = 27;
    public float INSULT_DECREASE_RELATIONS_BASE_PENALTY_RATIO = 0.4f;
    public float INSULT_DECREASE_RELATIONS_BASED_ON_CURRENT_RELATION_RATIO = 0.725f;
}
