package age.of.civilizations2.jakowski.lukasz.GameValues;

public class GV_Trade {
    public int COST_OFFER_TRADE_REQUEST_DIPLOMACY_POINTS = 16;
    public float DECLARE_WAR_CIV_POP_MODIFIER = 0.85f;
    public float DECLARE_WAR_CIV_GOLD_PER_ENEMY_UNIT = 10.0f;
    public float DECLARE_WAR_CIV_INCOME_MULTIPLIER = 23.5f;
    public int DECLARE_WAR_MAGIC_NUM_ALWAYS_ACCEPT = 666;
    public float AI_TRADE_MAX_PROVINCE_SHARE_TO_ACCEPT = 0.15f;
    public float AI_TRADE_PROVINCE_INCOME_TAXATION_WEIGHT = 1.5f;
    public float AI_TRADE_PROVINCE_INCOME_PRODUCTION_WEIGHT = 2.0f;
    public float AI_TRADE_PROVINCE_MIN_COST = 10.0f;
    public float AI_TRADE_PROVINCE_COST_MULTIPLIER = 225.0f;
    public float AI_TRADE_DEFENSIVE_INCOME_MULTIPLIER = 5.0f;
    public float AI_TRADE_DEFENSIVE_RELATION_GOLD_MAX = 50.0f;
    public float AI_TRADE_ACCEPT_PROVINCES_MAX_GOLD_PER_PROVINCE = 200.0f;
    public float AI_TRADE_ACCEPT_PROVINCES_ONLY_IF_TREASURY_AFTER_PAYING_IS_OVER = -2500.0f;
    public float AI_TRADE_MILITARY_ACCESS_BUDGET_MULTIPLIER_AT_WAR_WITH_FRIENDLY = 8.35f;
    public float AI_TRADE_MILITARY_ACCESS_BUDGET_MULTIPLIER_FROM_HATED_CIV = 2.35f;
    public float AI_TRADE_MILITARY_ACCESS_BUDGET_MULTIPLIER = 0.175f;
    public int PROCLAIM_INDEPENDENCE_MAX_PROVINCES = 10;
    public int PROCLAIM_THEIR_INDEPENDENCE_CIVS_LIMIT = 1;
    public boolean TRADE_REQUESTS_RESPONSE = true;
}
