package age.of.civilizations2.jakowski.lukasz.GameValues;

public class GV_Ultimatum {
    public int COST_ULTIMATUM_DIPLOMACY_POINTS = 24;
    public int ULTIMATUM_TRUCE_TURNS = 30;
    public int ULTIMATUM_TRUCE_TURNS_DEMAND_LIBERATION = 25;
    public int ULTIMATUM_REQUIRED_RELATIONS = -10;
    public float ULTIMATUM_VASSAL_LIBERTY_DESIRE_PERC_INCREASE = 1.25f;
    public float ULTIMATUM_VASSAL_LIBERTY_DESIRE_BASE_INCREASE = 18.0f;
    public int ULTIMATUM_VASSAL_LIBERTY_DESIRE_RANDOM_INCREASE = 36;
    public float ANNEXATION_HAPPINESS_CHANGE = 0.46f;
    public float ANNEXATION_REV_RISK_EXTRA_BASE = 0.065f;
    public int ANNEXATION_REV_RISK_EXTRA_RANDOM_100 = 11;
    public float ANNEX_PROVINCE_HAPPINESS_CHANGE = 0.54f;
    public float ANNEX_PROVINCE_RISK_EXTRA_BASE = 0.075f;
    public int ANNEX_PROVINCE_RISK_EXTRA_RANDOM_100 = 12;
}
