package age.of.civilizations2.jakowski.lukasz.GameValues;

public class GV_VassalLiberty {
    public float PROVINCE_RATIO_THRESHOLD = 1.1f;
    public float BASE_PROVINCE_LIBERTY_INCREASE = 0.425f;
    public int RANDOM_PROVINCE_LIBERTY_MAX_1000 = 825;
    public float PROVINCE_RATIO_MULTIPLIER = 0.85f;
    public float BASE_LIBERTY_HIGH_MULTIPLIER_PERC = 0.01f;
    public float BASE_TRIBUTE_HIGH_LIBERTY_INCREASE = 0.325f;
    public int RANDOM_TRIBUTE_HIGH_LIBERTY_100 = 100;
    public float TRIBUTE_LOW_THRESHOLD_MULTIPLIER = 0.5f;
    public float BASE_TRIBUTE_LOW_LIBERTY_DECREASE = 0.075f;
    public int RANDOM_TRIBUTE_LOW_LIBERTY_DECREASE_100 = 125;
    public int RELATION_NEGATIVE_THRESHOLD = -20;
    public float BASE_RELATION_LIBERTY_LOW_INCREASE = 2.425f;
    public float PASSIVE_LIBERTY_DECAY_PERC = 0.01f;
    public float MESSAGE_THE_PLAYER_IF_LIBERTY_OVER = 49.0f;
    public float LIBERTY_CHANGE_JUST_INFO_RANDOM_MODIFIER = 0.75f;
    public int SEND_VASSALS_HIGH_LIBERTY_MESSAGE_EVERY_X_TURNS = 4;
}
