package age.of.civilizations2.jakowski.lukasz.Save;

import age.of.civilizations2.jakowski.lukasz.AI.AI_ImproveRelations;
import age.of.civilizations2.jakowski.lukasz.AI.AI_Rival;
import age.of.civilizations2.jakowski.lukasz.CivBonus_GameData;
import age.of.civilizations2.jakowski.lukasz.CivInvest;
import age.of.civilizations2.jakowski.lukasz.CivInvest_Development;
import age.of.civilizations2.jakowski.lukasz.CivPersonality;
import age.of.civilizations2.jakowski.lukasz.CivPlans;
import age.of.civilizations2.jakowski.lukasz.CivTask;
import age.of.civilizations2.jakowski.lukasz.Civilization_Colonies;
import age.of.civilizations2.jakowski.lukasz.Civilization_Diplomacy_GameData;
import age.of.civilizations2.jakowski.lukasz.Civilization_Friends_GameData;
import age.of.civilizations2.jakowski.lukasz.Civilization_Hated_GameData;
import age.of.civilizations2.jakowski.lukasz.Civilization_Sanctions;
import age.of.civilizations2.jakowski.lukasz.Civilization_SentMessages;
import age.of.civilizations2.jakowski.lukasz.Civilizations.Civ_Gift_GameData;
import age.of.civilizations2.jakowski.lukasz.Civilizations.Civ_Mission_ChangeTypeOfGovernment;
import age.of.civilizations2.jakowski.lukasz.Civilizations.Construction.BuildingsConstruction;
import age.of.civilizations2.jakowski.lukasz.Civilizations.LoanCiv_GameData;
import age.of.civilizations2.jakowski.lukasz.Civilizations.Loan_GameData;
import age.of.civilizations2.jakowski.lukasz.GameValues.GameValues;
import age.of.civilizations2.jakowski.lukasz.LeaderOfCiv_GameData;
import age.of.civilizations2.jakowski.lukasz.RegroupArmy.RegroupArmy;
import age.of.civilizations2.jakowski.lukasz.TechPoints;
import age.of.civilizations2.jakowski.lukasz.Vassal_GameData;
import age.of.civilizations2.jakowski.lukasz.WarReparations;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ConcurrentHashMap;

public class Save_Civ_GameData
implements Serializable {
    private static final long serialVersionUID = 0L;
    public int iReligionID = 0;
    public int iGroupID = 0;
    public int puppetOfCivID;
    public float fVassalLibertyDesire = 0.0f;
    public LeaderOfCiv_GameData leaderData;
    public List<Vassal_GameData> vassals = new ArrayList<Vassal_GameData>();
    public int iVassalsSize = 0;
    public int iAIStyleID = 0;
    public CivPersonality civPers = new CivPersonality();
    public CivPlans civPlans = new CivPlans();
    public int iRegroupArmyAtPeace_CheckTurnID = 0;
    public String sCivTag;
    public String sCivName;
    public boolean isPartOfHolyRomaEmpire = false;
    public List<AI_Rival> civRivals = new ArrayList<AI_Rival>();
    public int civRivalsSize = 0;
    public int declareWarCheckNextTurnID = 0;
    public int nextArmyRestRegroupment_TurnID = 0;
    public int numOfUnions = 0;
    public float civAggressionLevel = 0.0f;
    public int resumeAllianceCheckAtTurnID = 0;
    public int allianceUpdate_TurnID = 0;
    public int circledVassals_TurnID = 0;
    public int checkFormCiv_TurnID = 0;
    public List<String> lEvents_DecisionsTaken = new ArrayList<String>();
    public Civilization_Diplomacy_GameData civDiploGD;
    public short iR;
    public short iG;
    public short iB;
    public List<RegroupArmy> lRegroupArmy;
    public int iRegroupArmySize;
    public List<Civilization_Colonies> coloniesFounded = new ArrayList<Civilization_Colonies>();
    public int resumeColonizationCheckAtTurnID = 1;
    public Civ_Mission_ChangeTypeOfGovernment changeTypeOfGovernment = null;
    public int expandNeutralProvinces_RangeCheck = 6;
    public int capitalProvinceID;
    public int coreCapitalProvinceID = -1;
    public int capitalMoved_LastTurnID;
    public int iNextPossibleNavalInvasionTurnID;
    public int nextBuildCivsInRange_TurnID;
    public int resumeLookingForRivalAtTurnID;
    public int resumeLookingForFriendsAtTurnID;
    public List<AI_ImproveRelations> civsToImproveRelationsWith;
    public int civsToImproveRelationsWithSize;
    public int policyID;
    public int iNukes;
    public List<Integer> nukesConstruction;
    public long iGE;
    public long iGEG;
    public long iGD;
    public int aACS;
    public long aACSG;
    public int fE;
    public long fECG;
    public int armyExpertiseLevel;
    public int armyExpertiseAttack;
    public int armyExpertiseDefense;
    public float armyExperience;
    public long ttWC;
    public int iPlunder_LastTurnID;
    public int iNextCheckMilitaryAccessTurnID;
    public int iNextCheckMilitaryAccessSeaTurnID;
    public int numOfConqueredProvinces;
    public int numOfBuildingsConstructed;
    public int recruitedArmy;
    public int iLockTreasury;
    public long startingPopulation;
    public long startingEconomy;
    public int iNumOfRevolutions;
    public boolean moveAtWar_ArmyFullyRecruitedLastTurn;
    public int moveAtWar_ProvincesLostAndConquered_LastTurn;
    public TechPoints techPoints;
    public float modifier_PopGrowth;
    public float modifier_EconomyGrowth;
    public float modifier_IncomeTaxation;
    public float modifier_IncomeProduction;
    public float modifier_Administration;
    public float modifier_Research;
    public float modifier_MilitaryUpkeep;
    public float modifier_AttackBonus;
    public float modifier_DefenseBonus;
    public float modifier_MovementPoints;
    public float modifier_ColonizationCost;
    public List<CivBonus_GameData> bonusesCiv;
    public int goldenAge_Prosperity;
    public int goldenAge_Military;
    public int goldenAge_Science;
    public int iNumOfTurnsAtWar;
    public float warWeariness;
    public long iGold;
    public List<Loan_GameData> loansTaken;
    public List<LoanCiv_GameData> lLoansTakenFromCiv;
    public List<WarReparations> warReparationsPay;
    public List<WarReparations> lWarReparationsGets;
    public int diploPoints;
    public int techLevel;
    public float spendingsResearch;
    public float spendingsInvestments;
    public float spendingsGoods;
    public float researchProgress;
    public float fTaxationLevel;
    public List<CivTask> festivals;
    public List<CivTask> assimilates;
    public List<CivInvest> investsEco;
    public List<CivInvest_Development> investsDev;
    public float numberOfInvestments;
    public List<BuildingsConstruction> lConstructions;
    public int allianceID;
    public ConcurrentHashMap<Integer, Float> relation;
    public int iRevolt_SinceTurn;
    public int iRevolt_LastTurnLostProvince;
    public List<Civilization_Hated_GameData> lHatedCivs;
    public int iHatedCivsSize;
    public List<Integer> lHatedCivs_By;
    public int iHatedCivs_BySize;
    public List<Civilization_Friends_GameData> friendlyCivs;
    public List<Civilization_SentMessages> sentMessages;
    public List<Civ_Gift_GameData> lGifts_Received;
    public List<Civilization_Sanctions> lSanctions;
    public boolean nationalBankBuilt;
    public long nationalBankReserves;

    public Save_Civ_GameData() {
        this.capitalMoved_LastTurnID = -GameValues.gvMoveCapital.MOVE_CAPITAL_LOCK_MOVING_FOR_X_TURNS;
        this.iNextPossibleNavalInvasionTurnID = 0;
        this.nextBuildCivsInRange_TurnID = 0;
        this.resumeLookingForRivalAtTurnID = 0;
        this.resumeLookingForFriendsAtTurnID = 1;
        this.civsToImproveRelationsWith = new ArrayList<AI_ImproveRelations>();
        this.civsToImproveRelationsWithSize = 0;
        this.policyID = 0;
        this.iNukes = 0;
        this.nukesConstruction = new ArrayList<Integer>();
        this.iGE = 0L;
        this.iGEG = 0L;
        this.iGD = 0L;
        this.aACS = 0;
        this.aACSG = 0L;
        this.fE = 0;
        this.fECG = 0L;
        this.armyExpertiseLevel = 0;
        this.armyExpertiseAttack = 0;
        this.armyExpertiseDefense = 0;
        this.armyExperience = 0.0f;
        this.ttWC = 0L;
        this.iPlunder_LastTurnID = 0;
        this.iNextCheckMilitaryAccessTurnID = 0;
        this.iNextCheckMilitaryAccessSeaTurnID = 0;
        this.numOfConqueredProvinces = 0;
        this.numOfBuildingsConstructed = 0;
        this.recruitedArmy = 0;
        this.iLockTreasury = 1;
        this.startingPopulation = 0L;
        this.startingEconomy = 0L;
        this.iNumOfRevolutions = 0;
        this.moveAtWar_ArmyFullyRecruitedLastTurn = false;
        this.moveAtWar_ProvincesLostAndConquered_LastTurn = 0;
        this.techPoints = new TechPoints();
        this.modifier_PopGrowth = 0.0f;
        this.modifier_EconomyGrowth = 0.0f;
        this.modifier_IncomeTaxation = 0.0f;
        this.modifier_IncomeProduction = 0.0f;
        this.modifier_Administration = 0.0f;
        this.modifier_Research = 0.0f;
        this.modifier_MilitaryUpkeep = 0.0f;
        this.modifier_AttackBonus = 0.0f;
        this.modifier_DefenseBonus = 0.0f;
        this.modifier_MovementPoints = 0.0f;
        this.modifier_ColonizationCost = 0.0f;
        this.bonusesCiv = new ArrayList<CivBonus_GameData>();
        this.goldenAge_Prosperity = 0;
        this.goldenAge_Military = 0;
        this.goldenAge_Science = 0;
        this.iNumOfTurnsAtWar = 0;
        this.warWeariness = 0.0f;
        this.spendingsResearch = 0.0f;
        this.spendingsInvestments = 0.16f;
        this.spendingsGoods = 0.2f;
        this.researchProgress = 0.0f;
        this.fTaxationLevel = 0.1f;
        this.festivals = new ArrayList<CivTask>();
        this.assimilates = new ArrayList<CivTask>();
        this.investsEco = new ArrayList<CivInvest>();
        this.investsDev = new ArrayList<CivInvest_Development>();
        this.numberOfInvestments = 0.0f;
        this.lConstructions = new ArrayList<BuildingsConstruction>();
        this.allianceID = 0;
        this.relation = new ConcurrentHashMap();
        this.iRevolt_SinceTurn = 1;
        this.iRevolt_LastTurnLostProvince = 1;
        this.lHatedCivs = new ArrayList<Civilization_Hated_GameData>();
        this.iHatedCivsSize = 0;
        this.lHatedCivs_By = new ArrayList<Integer>();
        this.iHatedCivs_BySize = 0;
        this.friendlyCivs = new ArrayList<Civilization_Friends_GameData>();
        this.sentMessages = new ArrayList<Civilization_SentMessages>();
        this.lGifts_Received = new ArrayList<Civ_Gift_GameData>();
        this.lSanctions = new ArrayList<Civilization_Sanctions>();
        this.nationalBankBuilt = false;
        this.nationalBankReserves = 0L;
    }
}
