package age.of.civilizations2.jakowski.lukasz.GameValues.AI;

public class GV_AI_CivsInRange {
    public float CIVS_IN_RANGE_DISTANCE_MODIFIER = 0.9f;
    public float CIVS_IN_RANGE_DISTANCE_EXTRA_MODIFIER = 0.2675f;
    public int REBUILD_CIVS_IN_RANGE_AFTER_X_TURNS = 129;
    public int REBUILD_CIVS_IN_RANGE_AFTER_X_TURNS_RANDOM = 69;
    public int REBUILD_CIVS_IN_RANGE_AFTER_X_TURNS_EMPTY = 49;
    public int REBUILD_CIVS_IN_RANGE_AFTER_X_TURNS_RANDOM_EMPTY = 52;
    public int REBUILD_CIVS_IN_RANGE_AFTER_X_TURNS_NO_CAPITAL = 34;
    public int REBUILD_CIVS_IN_RANGE_AFTER_X_TURNS_NO_CAPITAL_RANDOM = 41;
}
