package age.of.civilizations2.jakowski.lukasz.GameValues.AI;

public class GV_AI_Colonization {
    public int RESUME_COLONIZATION_AFTER_X_TURNS_IN_PROGRESS = 2;
    public int RESUME_COLONIZATION_AFTER_X_TURNS_IN_PROGRESS_RANDOM = 16;
    public int RESUME_COLONIZATION_AFTER_X_TURNS_INSUFFICIENT_TECH = 66;
    public int RESUME_COLONIZATION_AFTER_X_TURNS_INSUFFICIENT_TECH_RANDOM = 48;
    public int RESUME_COLONIZATION_AFTER_X_TURNS_INSUFFICIENT_GOLD = 12;
    public int RESUME_COLONIZATION_AFTER_X_TURNS_INSUFFICIENT_GOLD_RANDOM = 18;
    public float MAX_COLONIZATION_COST_TO_BUDGET_RATIO = 22.0f;
    public int RESUME_COLONIZATION_AFTER_TURNS_TOO_EXPENSIVE = 34;
    public int RESUME_COLONIZATION_AFTER_TURNS_TOO_EXPENSIVE_RANDOM = 42;
    public int RESUME_COLONIZATION_AFTER_X_TURNS_AT_WAR = 28;
    public int RESUME_COLONIZATION_AFTER_X_TURNS_AT_WAR_RANDOM = 24;
    public int RESUME_COLONIZATION_AFTER_X_TURNS_AFTER_COLONIZATION = 8;
    public int RESUME_COLONIZATION_AFTER_X_TURNS_AFTER_COLONIZATION_RANDOM = 26;
    public float RESUME_COLONIZATION_AFTER_X_TURNS_AFTER_COLONIZATION_SIZE_DIVISOR = 20.0f;
    public float TECH_GAP_REDUCTION_FACTOR = 0.35f;
    public int BASE_COLONIZATION_DIVISOR = 6;
    public int RANK_COLONIZATION_MULTIPLIER = 3;
    public int MAX_RANK_COLONIZATION_BONUS = 22;
    public float PROVINCE_SCALING_FACTOR = 0.01f;
    public float CAN_COLONIZE_TOP_CIVS_PERCENT = 0.35f;
    public int CAN_COLONIZE_TOP_CIVS_LIMIT = 16;
    public float COLONIZATION_SCORE_PER_OWN_NEIGH_PROVINCE = 0.725f;
}
