package age.of.civilizations2.jakowski.lukasz.GameValues.AI;

public class GV_AI_Relations {
    public int IMPROVE_RELATIONS_MIN_VALUE = 36;
    public int IMPROVE_RELATIONS_RANDOM = 40;
    public int IMPROVE_RELATIONS_MIN_NUM_OF_TURNS = 26;
    public int IMPROVE_RELATIONS_MIN_NUM_OF_TURNS_RANDOM = 40;
    public int RESUME_LOOKING_FOR_FRIENDS_AFTER_X_TURNS = 14;
    public int RESUME_LOOKING_FOR_FRIENDS_AFTER_X_TURNS_RANDOM = 26;
    public float IMPROVE_RELATIONS_BASE_BUDGET_MODIFIER = 1.85f;
    public int IMPROVE_RELATIONS_BUDGET_MODIFIER_RANDOM_RANGE_1000 = 475;
    public float IMPROVE_RELATIONS_BASE_CIV_SIZE_MODIFIER = 0.625f;
    public int IMPROVE_RELATIONS_CIV_SIZE_RANDOM_RANGE_1000 = 325;
    public float IMPROVE_RELATIONS_BASE_RANGE_MODIFIER = 0.2825f;
    public float IMPROVE_RELATIONS_RANGE_RANK_SCALING = 0.1475f;
    public float IMPROVE_RELATIONS_DISTANCE_MULTIPLIER = 0.2675f;
    public float IMPROVE_RELATIONS_RELATIONS_MODIFIER = 0.115f;
    public float IMPROVE_RELATIONS_BASE_BUDGET_SCALE = 0.625f;
    public int IMPROVE_RELATIONS_BUDGET_SCALE_RANDOM_RANGE_100 = 725;
    public int IMPROVE_RELATIONS_SCORE_RANDOM_RANGE_100 = 45;
    public int IMPROVE_RELATIONS_SKIP_IF_CIV_IMPROVES_RELATIONS_CHANCE_100 = 10;
    public int IMPROVE_RELATIONS_SKIP_IF_RELATIONS_OVER = 65;
    public float IMPROVE_RELATIONS_SCORE_RIVAL_OF_RIVAL_BONUS = 1.0625f;
    public int IMPROVE_RELATIONS_SCORE_RELATION_THRESHOLD = 50;
    public float IMPROVE_RELATIONS_SCORE_HIGH_RELATION_PENALTY = 0.625f;
}
