package age.of.civilizations2.jakowski.lukasz.GameValues.AI;

public class GV_AI_Budget {
    public int BUDGET_MAX = 300;
    public int MAX_RESEARCH_IF_GOLD_OVER = 999999;
    public float WAR_BASE_HAPPINESS = 0.7f;
    public int WAR_HAPPINESS_THRESHOLD_VERY_LOW = 20;
    public int WAR_HAPPINESS_THRESHOLD_LOW = 40;
    public int WAR_HAPPINESS_THRESHOLD_MEDIUM = 55;
    public int WAR_HAPPINESS_THRESHOLD_HIGH = 80;
    public float WAR_HAPPINESS_DIVISOR_VERY_LOW = 16.0f;
    public float WAR_HAPPINESS_DIVISOR_LOW = 4.0f;
    public float WAR_HAPPINESS_DIVISOR_MEDIUM = 2.0f;
    public float WAR_MIN_PROVINCE_HAPPINESS_RUN_FESTIVAL_MODIFIER = 115.0f;
    public int WAR_HAPPINESS_HIGH_RANDOM_1000 = 1450;
    public float BASE_HAPPINESS = 0.7f;
    public int HAPPINESS_THRESHOLD_VERY_LOW = 20;
    public int HAPPINESS_THRESHOLD_LOW = 40;
    public int HAPPINESS_THRESHOLD_MEDIUM = 55;
    public int HAPPINESS_THRESHOLD_HIGH = 80;
    public float HAPPINESS_DIVISOR_VERY_LOW = 16.0f;
    public float HAPPINESS_DIVISOR_LOW = 4.0f;
    public float HAPPINESS_DIVISOR_MEDIUM = 2.0f;
    public float MIN_PROVINCE_HAPPINESS_RUN_FESTIVAL_MODIFIER = 115.0f;
    public int HAPPINESS_HIGH_RANDOM_1000 = 1450;
    public float WAR_GOLD_RESERVE_BASE = 0.675f;
    public float WAR_GOLD_RESERVE_LOW = 0.25f;
    public float WAR_GOLD_RESERVE_REDUCTION_BASE = 0.4f;
    public float WAR_GOLD_RESERVE_REDUCTION_SCALE = 0.375f;
    public float GOLD_RESERVE_BASE = 1.0f;
    public float GOLD_RESERVE_LOCKED = 0.275f;
    public float GOLD_RESERVE_LOCKED_BONUS = 0.225f;
    public float GOLD_RESERVE_ASSIMILATION_MIN = 0.1f;
    public float GOLD_RESERVE_ASSIMILATION_SCALE = 0.9f;
    public float GOLD_RESERVE_TREASURY_MAX = 2.25f;
    public float GOLD_RESERVE_TREASURY_DECREASE = 0.75f;
    public float WAR_TOTAL_BUDGET_BASE = 0.97f;
    public float WAR_NO_MONEY_SPENDING_MIN = 0.04f;
    public int WAR_NO_MONEY_SPENDING_RAND_100 = 46;
    public float TOTAL_BUDGET_BASE = 0.97f;
    public float NO_MONEY_SPENDING_MIN = 0.04f;
    public int NO_MONEY_SPENDING_RAND_100 = 46;
    public int EXTRA_RESEARCH_EVERY_X_TURN = 27;
    public int EXTRA_RESEARCH_MIN_GOLD = 1000;
    public float EXTRA_RESEARCH_MIN = 0.3f;
    public int EXTRA_RESEARCH_RAND_100 = 32;
}
