name: Generate Javadoc

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Clean decompiled code
        run: |
          find . -name "*.java" -exec sed -i 's/\*\* GOTO.*;//g' {} +
          find . -name "*.java" -exec sed -i 's/lbl[0-9]*://g' {} +
          find . -name "*.java" -exec sed -i 's/ArrayList<[0-9]*>/ArrayList/g' {} +
          find . -name "*.java" -exec sed -i 's/[0-9]\.get/0 .get/g' {} +

      - name: Generate Javadoc
        run: |
          mkdir -p docs/javadoc
          javadoc -d docs/javadoc \
            -encoding UTF-8 \
            -docencoding UTF-8 \
            -charset UTF-8 \
            -Xdoclint:none \
            -quiet \
            -subpackages age:aoc

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/javadoc
          branch: gh-pages
